### ISSUE TITLE
Cannot add dependency to a .NET Core 1.1 project

### ISSUE THREAD

**Issue by epot** [chrisdrobison/aspnetcore-wsfed#15]
I am trying to add the 1.0.2 version as a Nuget package to my project, but end up with a:

    Package AspNetCore.Authentication.WsFederation 1.0.2 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package AspNetCore.Authentication.WsFederation 1.0.2 supports: net452 (.NETFramework,Version=v4.5.2)
    One or more packages are incompatible with .NETCoreApp,Version=v1.1.

**Comment by chrisdrobison** [comment]
Yes, that is correct. The readme states this project has a hard dependency on the full framework because all the working WsFed libraries only exist in the full framework. As soon as the new WsFed libraries come with .NET Core 2.1, there won't be a need for the library anymore as supposedly the ASP.NET team will have released their implementation using the new library.

The updated library for WsFed is being developed here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet. The nightly builds are available on MyGet.

**Comment by epot** [comment]
Maybe I am missing the point, but does that mean I cannot depend on this library if I am using .net core?

**Comment by chrisdrobison** [comment]
Correct. You can use ASP.NET Core (not be confused with .NET Core), but you'll have to target the full framework.

**Comment by epot** [comment]
Oh I did not get the subtle difference :). Thanks for the clarification!
