### ISSUE TITLE
[Authorize] -  Attribute not redirecting to login

### ISSUE THREAD

**Issue by Compufreak345** [chrisdrobison/aspnetcore-wsfed#2]
Hi, it's me again ;)

If I add the [Authorize]-Attribute to a class, it does not redirect to login like it did with the .NET 4.5-version.

I think this might be related to the MVC6 Authorize-Attribute missing the 
`public virtual void OnAuthorization(AuthorizationContext filterContext);`
method (see http://stackoverflow.com/a/35863514/3085985 ).

I am not sure if it is appropriate to implement this in your library, if I should implement a filter for this myself, or if this would be good to have in the example. I could try implementing a filter, probably tomorrow, and share my results if it should be in the example.

What do you think?

Thanks & best regards,
Christoph

**Comment by chrisdrobison** [comment]
As far as I understand it, this kind of thing needs to happen outside the middleware. The middleware's purpose is to solely establish a ClaimsPrincipal. What the [Authorize] attributes do with that afterwards is their business.

**Comment by Compufreak345** [comment]
Sounds reasonable - I'll implement the redirecting filter. Are you interested in the code for your example? Otherwise you can close this issue.

**Comment by chrisdrobison** [comment]
Sure, I could add it to the sample

**Comment by Compufreak345** [comment]
Great - I'll try to provide the code during this week.

**Comment by ekhanna26** [comment]
@Compufreak345 - Hi there, I am facing same scenario in my app and would like to do redirects from the controller action. I am using ADFS for the authentication and would also be interested in the code example that you are working on. Thanks!

**Comment by Compufreak345** [comment]
During my research for the example, after wondering why the redirect works out of the box on other .NET Core projects with preset "Individual User Accounts"-Authentication. I stumpled accross this post : https://andrewlock.net/exploring-the-cookieauthenticationmiddleware-in-asp-net-core/ that hints me that Microsoft seems to see the redirection as supposed to be part of the middleware.
So, I went over to https://github.com/aspnet/Security , searched for LoginPath - and tried to port this code to your middleware - and am a bit stuck now :>

I'm having quite a hard time understanding what exactly I would have to add. I found out it's the  
`protected override async Task<AuthenticateResult> HandleAuthenticateAsync()` ( https://github.com/aspnet/Security/blob/0152691108717bd74cc5f0406e7b745b31c8ca23/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L121 ) where a breakpoint hits after adding the [Authorize] attribute, and the `protected override async Task<bool> HandleUnauthorizedAsync(ChallengeContext context) ` ( https://github.com/aspnet/Security/blob/0152691108717bd74cc5f0406e7b745b31c8ca23/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L379 )method doing the redirect 
 but I'm not sure how this is supposed to be implemented into your project, as the events are quite different from those implemented in Microsofts code. 

@chrisdrobison Can you have a look into this or give me a hint in the right direction?

**Comment by chrisdrobison** [comment]
This middleware hands off authentication to the cookie middleware, or at
least it should be. Try turning on tracing in the logging to see what comes
back.

On Thu, Mar 23, 2017 at 4:18 AM Compufreak345 <notifications@github.com>
wrote:

During my research for the example, after wondering why the redirect works
out of the box on other .NET Core projects with preset "Individual User
Accounts"-Authentication. I stumpled accross this post :
https://andrewlock.net/exploring-the-cookieauthenticationmiddleware-in-asp-net-core/
that hints me that Microsoft seems to see the redirection as supposed to be
part of the middleware.
So, I went over to https://github.com/aspnet/Security , searched for
LoginPath - and tried to port this code to your middleware - and am a bit
stuck now :>

I'm having quite a hard time understanding what exactly I would have to
add. I found out it's the
protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
(
https://github.com/aspnet/Security/blob/0152691108717bd74cc5f0406e7b745b31c8ca23/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L121
)
that needs to be added, but I'm not sure what to do afterwards.

@chrisdrobison <https://github.com/chrisdrobison> Can you have a look into
this? Or should I still try to workaround with filters?

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/chrisdrobison/aspnetcore-wsfed/issues/2#issuecomment-288674951>,
or mute the thread

**Comment by Compufreak345** [comment]
Thanks for your hints - they helped me to find the correct message to search for ;) Based on http://stackoverflow.com/questions/36967426/asp-net-core-authorize-redirection-not-happening and https://msdn.microsoft.com/en-us/library/microsoft.owin.security.cookies.cookieauthenticationoptions(v=vs.113).aspx I was able to implement redirection, together with returning to the URL where the redirection started. 

I submitted a pull request to make your sample demonstrate this. https://github.com/chrisdrobison/aspnetcore-wsfed/pull/3 
Any kind of feedback would be greatly appreciated :)

P.S.: In your project I couldn't completely test everything as I don't have a login for your AD, but it should work as it did in my project.
